package components

import (
	"github.com/nobonobo/spago"
)

// Render ...
func (c *Header) Render() spago.HTML {
	return spago.Tag("div", 		
		spago.A("class", spago.S(`uk-position-top`)),
		spago.Tag("nav", 			
			spago.A("class", spago.S(`uk-navbar-container uk-navbar-transparent`)),
			spago.A("uk-navbar", spago.S(`true`)),
			spago.Tag("div", 				
				spago.A("class", spago.S(`uk-navbar-center`)),
				spago.Tag("a", 					
					spago.A("class", spago.S(`uk-navbar-item uk-logo`)),
					spago.A("href", spago.S(`#`)),
					spago.T(`SpagoThree`),
				),
				spago.Tag("ul", 					
					spago.A("class", spago.S(`uk-navbar-nav`)),
					spago.Tag("li", 
						spago.Tag("a", 							
							spago.A("href", spago.S(`#`)),
							spago.T(`Fundamental`),
						),
						spago.Tag("div", 							
							spago.A("class", spago.S(`uk-navbar-dropdown`)),
							spago.Tag("ul", 								
								spago.A("class", spago.S(`uk-nav uk-navbar-dropdown-nav`)),
								spago.Tag("li", 
									spago.Tag("a", 										
										spago.A("href", spago.S(`#/f1`)),
										spago.T(`SimpleCubes`),
									),
								),
								spago.Tag("li", 
									spago.Tag("a", 										
										spago.A("href", spago.S(`#/f2`)),
										spago.T(`InteractiveCubes`),
									),
								),
								spago.Tag("li", 
									spago.Tag("a", 										
										spago.A("href", spago.S(`#/f3`)),
										spago.T(`SceneGraph`),
									),
								),
								spago.Tag("li", 
									spago.Tag("a", 										
										spago.A("href", spago.S(`#/f4`)),
										spago.T(`Texture`),
									),
								),
								spago.Tag("li", 
									spago.Tag("a", 										
										spago.A("href", spago.S(`#/f5`)),
										spago.T(`Light`),
									),
								),
								spago.Tag("li", 
									spago.Tag("a", 										
										spago.A("href", spago.S(`#/f6`)),
										spago.T(`Camera`),
									),
								),
								spago.Tag("li", 
									spago.Tag("a", 										
										spago.A("href", spago.S(`#/f7`)),
										spago.T(`Shadow1`),
									),
								),
								spago.Tag("li", 
									spago.Tag("a", 										
										spago.A("href", spago.S(`#/f8`)),
										spago.T(`Shadow2`),
									),
								),
								spago.Tag("li", 
									spago.Tag("a", 										
										spago.A("href", spago.S(`#/f9`)),
										spago.T(`Fog`),
									),
								),
							),
						),
					),
					spago.Tag("li", 
						spago.Tag("a", 							
							spago.A("href", spago.S(`#`)),
							spago.T(`Extra`),
						),
						spago.Tag("div", 							
							spago.A("class", spago.S(`uk-navbar-dropdown`)),
							spago.Tag("ul", 								
								spago.A("class", spago.S(`uk-nav uk-navbar-dropdown-nav`)),
								spago.Tag("li", 
									spago.Tag("a", 										
										spago.A("href", spago.S(`#/miku1`)),
										spago.T(`MMD`),
									),
								),
							),
						),
					),
				),
			),
		),
	)
}
